"""initial schema and sample Russian scripts

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-31
"""
from alembic import op
import sqlalchemy as sa
revision="0001_initial"; down_revision=None; branch_labels=None; depends_on=None
def upgrade():
    op.create_table("business_connections",sa.Column("id",sa.String(255),primary_key=True),sa.Column("business_user_id",sa.BigInteger(),nullable=False),sa.Column("is_enabled",sa.Boolean(),nullable=False,server_default=sa.true()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table("scripts",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("title",sa.String(255),nullable=False),sa.Column("text",sa.Text(),nullable=False),sa.Column("language",sa.String(16),nullable=False),sa.Column("category",sa.String(64),nullable=False),sa.Column("stage",sa.String(64),nullable=False),sa.Column("active",sa.Boolean(),nullable=False))
    op.create_table("clients",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("chat_id",sa.BigInteger(),nullable=False,unique=True),sa.Column("telegram_user_id",sa.BigInteger()),sa.Column("username",sa.String(255)),sa.Column("first_name",sa.String(255)),sa.Column("language",sa.String(16)),sa.Column("category",sa.String(64)),sa.Column("business_connection_id",sa.String(255),nullable=False),sa.Column("last_incoming_at",sa.DateTime(timezone=True)),sa.Column("last_outgoing_at",sa.DateTime(timezone=True)),sa.Column("last_message_text",sa.Text()),sa.Column("status",sa.String(32),nullable=False),sa.Column("last_followup_at",sa.DateTime(timezone=True)),sa.Column("used_script_id",sa.Integer(),sa.ForeignKey("scripts.id")),sa.Column("sends_count",sa.Integer(),nullable=False),sa.Column("replied_after_followup",sa.Boolean(),nullable=False),sa.Column("excluded",sa.Boolean(),nullable=False),sa.Column("paused",sa.Boolean(),nullable=False),sa.Column("blocked",sa.Boolean(),nullable=False),sa.Column("deleted",sa.Boolean(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("updated_at",sa.DateTime(timezone=True),server_default=sa.func.now()))
    op.create_table("followup_queue",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("client_id",sa.Integer(),sa.ForeignKey("clients.id"),nullable=False),sa.Column("script_id",sa.Integer(),sa.ForeignKey("scripts.id"),nullable=False),sa.Column("run_date",sa.DateTime(timezone=True),nullable=False),sa.Column("scheduled_at",sa.DateTime(timezone=True),nullable=False),sa.Column("status",sa.Enum("pending","sent","cancelled","failed","paused",name="queuestatus"),nullable=False),sa.Column("error",sa.Text()),sa.UniqueConstraint("client_id","run_date",name="uq_queue_client_day"))
    op.create_table("send_logs",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("client_id",sa.Integer(),sa.ForeignKey("clients.id")),sa.Column("chat_id",sa.BigInteger(),nullable=False),sa.Column("sent_at",sa.DateTime(timezone=True),server_default=sa.func.now()),sa.Column("script_id",sa.Integer(),sa.ForeignKey("scripts.id")),sa.Column("status",sa.String(32),nullable=False),sa.Column("error",sa.Text()),sa.Column("business_connection_id",sa.String(255),nullable=False))
    op.bulk_insert(sa.table("scripts",sa.column("title",sa.String),sa.column("text",sa.Text),sa.column("language",sa.String),sa.column("category",sa.String),sa.column("stage",sa.String),sa.column("active",sa.Boolean)),[{"title":"Мягкое напоминание 1","text":"Здравствуйте! Возвращаюсь к нашему разговору. Подскажите, вопрос ещё актуален?","language":"ru","category":"general","stage":"followup","active":True},{"title":"Мягкое напоминание 2","text":"Добрый день! Хотел уточнить, удалось ли вам принять решение по нашему предложению? Буду рад помочь.","language":"ru","category":"general","stage":"followup","active":True},{"title":"English follow-up","text":"Hello! I am following up on our previous conversation. Is this still relevant for you?","language":"en","category":"general","stage":"followup","active":True}])
def downgrade():
    op.drop_table("send_logs");op.drop_table("followup_queue");op.drop_table("clients");op.drop_table("scripts");op.drop_table("business_connections");op.execute("DROP TYPE IF EXISTS queuestatus")
